/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * clientFrame.java
 *
 * Created on Feb 10, 2014, 5:48:13 PM
 */
package echoserverup_iterative;

/**
 *
 * @author PULAK
 */
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class clientFrame extends javax.swing.JFrame implements Runnable{
    
   
    Thread t;
     int clln_no;
    /** Creates new form clientFrame */
    public clientFrame(int cln_no) throws IOException{
        initComponents();
         clln_no=cln_no;
        t = new Thread(this);
t.start();     
    }
         String b = "123" ;
    Socket soc[] = new Socket[100];//       
    String str[] = new String[100];
    BufferedReader br[] = new BufferedReader[100];
    DataOutputStream dos[] =new DataOutputStream[100];
     String s, s1;
     //BufferedReader kyrd= new BufferedReader(new InputStreamReader(System.in));
   BufferedReader kyrd= new BufferedReader(new InputStreamReader(System.in));
 public void run() {
        try {

         soc[clln_no] = new Socket("127.0.0.1",2000);
        System.out.print(soc[clln_no].isConnected());
        
    
    
    
        br[clln_no] = new BufferedReader(new InputStreamReader(soc[clln_no].getInputStream()));
        dos[clln_no] = new DataOutputStream(soc[clln_no].getOutputStream());
    
    System.out.println("To start the dialog type the message in this client window \n Type exit to end"); 
     boolean more = true;
     jTextField1.setText("type here");
//while (true) {
    
    
       //  b =jTextField1.getSelectedText();        

       
    //    if (s.equals("exit")) {
      //      break;
      //  }
        
    
        
//}
 
      br[clln_no].close();
     dos[clln_no].close();

     soc[clln_no].close();

   
  
        } catch (UnknownHostException ex) {
            Logger.getLogger(SimpleClient1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SimpleClient1.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(echoserverup_iterative.EchoserverupApp.class).getContext().getResourceMap(clientFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try {
            // TODO add your handling code here:
               
             b =jTextField1.getSelectedText();        
  jTextField1.setText("");
   str[clln_no] = b;
       
            //str[clln_no]=kyrd.readLine();
         //dos[clln_no].writeBytes(str[clln_no]);
         dos[clln_no].writeBytes(b);
         dos[clln_no].write(13);
         dos[clln_no].write(10);
         dos[clln_no].flush();
       
        s =  br[clln_no].readLine();
        jTextArea1.setText("From server :" +s);
        System.out.println("From server :" + s);
        } catch (IOException ex) {
            Logger.getLogger(clientFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
  
  
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            
            
            
            
            
            public void run() {
                try {
                    int sa=1;
                    new clientFrame(sa).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(clientFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
