/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SERVER_WIN.java
 *
 * Created on Feb 11, 2014, 8:44:34 AM
 */
package final_os_project;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.PrintStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.net.ServerSocket;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author PULAK
 */
public class SERVER_WIN extends javax.swing.JFrame implements Runnable{
 Thread t;
    /** Creates new form SERVER_WIN */
    public SERVER_WIN() throws IOException{
        initComponents();
         t = new Thread(this);
          t.start();     
        
    }
    
      public void run() {
        
        ServerSocket echoServer = null;
    String line = null,linee = null;
    //DataInputStream is;
    BufferedReader br = null;
    //PrintStream os;
    DataOutputStream dos = null;
    Socket clientSocket = null;
    try {
      echoServer = new ServerSocket(2222);
    } catch (IOException e)
    {
      System.out.println(e);
    }
        
       jTextArea1.setText("The server started. To stop it press <CTRL><C>.");
    System.out.println("The server started. To stop it press <CTRL><C>.");
    try {
      clientSocket = echoServer.accept();
      if(clientSocket.isConnected())
      {
          linee="connected with client at:"+clientSocket;
      jTextArea1.setText(linee);
     // is = new DataInputStream(clientSocket.getInputStream());
       br = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
      //os = new PrintStream(clientSocket.getOutputStream());
        dos = new DataOutputStream(clientSocket.getOutputStream());
boolean quit = false;
      /* As long as we receive data, echo that data back to the client. */
      do {
        String msg = "";
                try {
                    line = br.readLine();
                } catch (IOException ex) {
                    //Logger.getLogger(newServerClass_2.class.getName()).log(Level.SEVERE, null, ex);
                }
                int len = line.length();
                if (line.equals("exit")) {
                    quit = true;
                }
                for (int i = 0; i < len; i++) {
                    msg = msg + line.charAt(i);
                    dos .write((byte)line.charAt(i));
                }
        //os.println("From server: " + line);
        //dos.writeBytes(str);
        dos.write(13);
        dos.write(10);
        dos.flush();
        
        linee= linee +"\nclient:"+msg;
        jTextArea1.setText(linee);
      } while (!quit);
      }
      else
      {
      System.out.println("notconnected with client");
      }
      
    } catch (IOException e) {
      System.out.println(e);
    }
        
           
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(final_os_project.Final_os_projectApp.class).getContext().getResourceMap(SERVER_WIN.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new SERVER_WIN().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SERVER_WIN.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
